name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    name: OS ${{ matrix.os}} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox tox-gh-actions

      - name: Set locale ubuntu
        if: runner.os == 'Linux'
        run: sudo locale-gen fa_IR

      - name: Tox tests
        run: |
          tox -v

  flake8:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox tox-gh-actions

      - name: Run flake8
        run: |
          tox -e flake8

  isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox tox-gh-actions

      - name: Run isort
        run: |
          tox -e isort